"""Synthesise the ship's machinery to assets/generated/sfx/*.wav.

Run:
    python tools/build_sfx.py

Why this exists
---------------
None of these sounds can be recorded, because none of them exist: a leadscrew
heard through a pressure bulkhead in vacuum has no field recording. They are
built from first principles instead, which also makes them ours outright — see
CREDITS.md, assets/generated/sfx/ carries no licence constraint.

Committed output, like tools/build_hull.py: a clone must run without Python.

The one rule
------------
Outside the hull there is no air, so nothing out there radiates sound to you.
Every sound here arrives by one of two paths:

  STRUCTURE  conducted through the frame. No crisp top end, smeared by the
             frame's ring. Everything mounted outside: gear, door, cutter head,
             thrusters, drive.
  CABIN      the cabin's own air. The only sounds with any high end. The
             ventilation, the annunciator, your own headset.

The hull's colouring itself is NOT baked in here — it lives on the STRUCTURE
audio bus, built in systems/audio/AudioSystem.gd, so these clips are authored
clean and every one of them picks up the same signature for free. What IS baked
in is the character each machine has of its own: a leadscrew's per-rev wobble,
three legs that do not arrive together, a coolant pump that runs on after
shutdown.

Seamless loops
--------------
Every _loop clip is generated by filtering in the FFT domain, which is CIRCULAR
convolution — the result is inherently periodic over its own length, so the loop
point is sample-exact with no crossfade. Any modulation applied to a loop must
therefore complete a WHOLE number of cycles across the buffer; see cycles().
"""

import os
import wave

import numpy as np

# 32 kHz is generous for this set: the structure-borne half is lowpassed under a
# kilohertz by the bus anyway, and the brightest thing here is an annunciator
# tone. It costs a third less than 44.1 for no audible difference.
SR = 32000

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "assets", "generated", "sfx")

# One RNG, seeded, so a rebuild produces byte-identical files and a rerun never
# shows up as a spurious diff.
RNG = np.random.default_rng(20260826)


# --- Primitives -----------------------------------------------------------------

def n(seconds):
    """Sample count for a duration."""
    return int(round(seconds * SR))


def t(count):
    """Time axis, seconds."""
    return np.arange(count) / SR


def cycles(count, hz):
    """A modulation phase that completes a WHOLE number of cycles over `count`.

    Using this instead of a raw frequency is what keeps a loop seamless: a
    wobble that is mid-cycle at the loop point clicks.
    """
    whole = max(1, int(round(hz * count / SR)))
    return np.linspace(0.0, 2.0 * np.pi * whole, count, endpoint=False)


def noise(count):
    return RNG.standard_normal(count)


def spectral(sig, shape):
    """Filter by multiplying the spectrum. Circular, so loops stay seamless.

    `shape` is called with the real-FFT frequency axis in Hz and returns a gain
    per bin.
    """
    spec = np.fft.rfft(sig)
    freq = np.fft.rfftfreq(len(sig), 1.0 / SR)
    return np.fft.irfft(spec * shape(freq), len(sig))


def lowpass(sig, cutoff, order=2):
    return spectral(sig, lambda f: 1.0 / np.sqrt(1.0 + (f / cutoff) ** (2 * order)))


def highpass(sig, cutoff, order=2):
    def shape(f):
        ratio = np.divide(cutoff, np.maximum(f, 1e-9))
        return 1.0 / np.sqrt(1.0 + ratio ** (2 * order))
    return spectral(sig, shape)


def bandpass(sig, low, high, order=2):
    return lowpass(highpass(sig, low, order), high, order)


def pink(count):
    """Noise with a 1/sqrt(f) spectrum — the duct-rush and rumble substrate."""
    def shape(f):
        return 1.0 / np.sqrt(np.maximum(f, 1.0))
    return norm(spectral(noise(count), shape))


def resonance(sig, hz, q, gain):
    """Lift one narrow band — a cabin mode, a panel ringing, a duct."""
    def shape(f):
        width = hz / q
        return 1.0 + gain * np.exp(-0.5 * ((f - hz) / width) ** 2)
    return spectral(sig, shape)


def norm(sig, peak=1.0):
    top = np.max(np.abs(sig))
    return sig * (peak / top) if top > 1e-12 else sig


def fade(sig, rise=0.005, fall=0.02):
    """Top and tail a one-shot so it neither clicks in nor cuts off."""
    out = sig.copy()
    a, b = n(rise), n(fall)
    if a > 0:
        out[:a] *= np.linspace(0.0, 1.0, a)
    if b > 0:
        out[-b:] *= np.linspace(1.0, 0.0, b)
    return out


def decay(count, tau):
    """Exponential decay envelope — how a struck frame gives its energy back."""
    return np.exp(-t(count) / tau)


def thump(seconds, hz, tau, detune=0.35):
    """A damped low-frequency frame mode: something heavy arriving on a stop.

    Two partials rather than one, slightly inharmonic, because a hull section is
    a plate and not a string.
    """
    count = n(seconds)
    env = decay(count, tau)
    body = np.sin(2 * np.pi * hz * t(count))
    body += 0.45 * np.sin(2 * np.pi * hz * (1.0 + detune) * t(count))
    # A little noise inside the attack is the impact itself, before the frame
    # settles into its modes.
    body += 0.5 * lowpass(noise(count), hz * 4.0) * decay(count, tau * 0.12)
    return fade(norm(body * env) * 0.9, 0.001, 0.01)


def click(seconds, low, high, tau):
    """A small, dry mechanical event — lock pins, a contactor, a valve seat."""
    count = n(seconds)
    return fade(norm(bandpass(noise(count), low, high) * decay(count, tau)) * 0.8,
                0.0005, 0.004)


def place(canvas, sig, at):
    """Mix a clip into a canvas at a time offset, clipping at the end."""
    start = n(at)
    end = min(len(canvas), start + len(sig))
    if start < len(canvas):
        canvas[start:end] += sig[:end - start]
    return canvas


def write(name, sig, peak=0.85):
    """16-bit mono WAV. Godot imports these natively; loop mode is set in code."""
    os.makedirs(OUT_DIR, exist_ok=True)
    # Strip DC before normalising. Asymmetric sources — a gated crackle, a pump
    # throb — leave an offset that buys nothing, eats headroom, and thumps the
    # speaker when the clip starts or stops.
    data = np.clip(norm(sig - np.mean(sig), peak), -1.0, 1.0)
    pcm = (data * 32767.0).astype(np.int16)
    path = os.path.join(OUT_DIR, name + ".wav")
    with wave.open(path, "wb") as f:
        f.setnchannels(1)
        f.setsampwidth(2)
        f.setframerate(SR)
        f.writeframes(pcm.tobytes())
    print("  %-24s %5.2f s  %6.1f KB" % (name, len(sig) / SR, os.path.getsize(path) / 1024.0))


# --- Ventilation ----------------------------------------------------------------

def build_ventilation():
    """The bed, and the only airborne machine on the ship.

    Duct rush shaped by two cabin modes, the fan's blade-pass tone, and a slow
    beat between two fans running slightly out of sync. This is the sound whose
    ABSENCE does the work: when the LIFE channel dies the room goes silent and
    the vacuum outside becomes real.
    """
    count = n(4.0)
    air = pink(count)
    air = resonance(air, 180.0, 3.0, 1.8)   # cabin mode
    air = resonance(air, 440.0, 5.0, 0.9)   # duct
    air = lowpass(air, 5200.0, 1)           # nothing is truly bright in here
    air = norm(air) * 0.55

    # Blade pass: seven blades at about forty revolutions a second.
    blade = 0.10 * np.sin(cycles(count, 280.0))
    blade += 0.04 * np.sin(cycles(count, 560.0))

    # The second fan is a hair off the first, so the pair beats slowly.
    beat = 1.0 + 0.10 * np.sin(cycles(count, 0.3))

    write("vent_loop", (air + blade) * beat)


# --- Landing gear ---------------------------------------------------------------

def _jack(count, base, wobble_hz):
    """One screw-jack: a whine plus the rumble of a leg in its guide."""
    whine = 0.55 * np.sin(cycles(count, base))
    whine += 0.30 * np.sin(cycles(count, base * 2.0))
    whine += 0.12 * np.sin(cycles(count, base * 3.0))
    # Per-rev wobble — a jack under load is never perfectly smooth.
    whine *= 1.0 + 0.22 * np.sin(cycles(count, wobble_hz))
    grind = 0.35 * lowpass(pink(count), 700.0)
    return whine + grind


def build_gear():
    """Three legs, and they do not arrive together.

    The legs are outside, in vacuum, so structure is the ONLY path — there is no
    air rush anywhere in this set. Compare the cargo door, which has a pressure
    bulkhead between it and you.
    """
    count = n(1.5)
    # Three jacks, detuned. Real hardware is never matched, and three separate
    # notes beating against each other is what stops this reading as one motor.
    legs = _jack(count, 148.0, 4.0)
    legs += 0.85 * _jack(count, 163.0, 3.6)
    legs += 0.80 * _jack(count, 139.0, 4.4)
    write("gear_travel_loop", norm(legs) * 0.7)

    # Down-and-locked: three legs onto their downlocks, staggered ~120 ms.
    canvas = np.zeros(n(1.4))
    for i, (at, hz, tau) in enumerate([(0.0, 74.0, 0.30), (0.13, 68.0, 0.34), (0.27, 81.0, 0.28)]):
        place(canvas, thump(0.7, hz, tau), at)
        place(canvas, click(0.10, 1400.0, 6000.0, 0.012) * 0.35, at + 0.03)
    write("gear_lock_down", canvas)

    # Up-and-stowed: tighter, higher, less mass arriving — the leg is being
    # pulled into a bay, not taking the ship's weight.
    canvas = np.zeros(n(1.2))
    for at, hz, tau in [(0.0, 96.0, 0.20), (0.11, 88.0, 0.22), (0.23, 104.0, 0.18)]:
        place(canvas, thump(0.5, hz, tau) * 0.8, at)
        place(canvas, click(0.08, 1800.0, 7000.0, 0.010) * 0.3, at + 0.02)
    write("gear_lock_up", canvas)


# --- Cargo door -----------------------------------------------------------------

def build_hatch():
    """The one machine with a bulkhead between it and you.

    The hold is not the cabin. The leadscrew reaches you through the frame like
    everything else outside — but the hold's residual AIR reaches you through the
    bulkhead, and that is the only reason this set sounds different from the
    gear. Opening dumps that air and you hear it go; closing repressurises and
    you hear it arrive.
    """
    count = n(1.6)
    # A single big leadscrew, slower and heavier than a gear jack.
    screw = 0.60 * np.sin(cycles(count, 92.0))
    screw += 0.35 * np.sin(cycles(count, 184.0))
    screw += 0.16 * np.sin(cycles(count, 276.0))
    screw *= 1.0 + 0.30 * np.sin(cycles(count, 4.0))     # per-rev wobble
    track = 0.45 * lowpass(pink(count), 420.0)           # door in its track
    write("hatch_travel_loop", norm(screw + track) * 0.7)

    # The hold dumping what air it still held, heard THROUGH the bulkhead. The
    # band falls as the pressure does, because there is progressively less air
    # to carry the high end — it does not fade out, it runs out.
    count = n(0.9)
    gasp = noise(count)
    bands = np.zeros(count)
    steps = 12
    for i in range(steps):
        lo, hi = i / steps, (i + 1) / steps
        seg = bandpass(gasp, 200.0 + 2600.0 * (1.0 - lo), 400.0 + 5000.0 * (1.0 - lo), 2)
        mask = np.zeros(count)
        mask[int(lo * count):int(hi * count)] = 1.0
        bands += seg * mask
    bands *= decay(count, 0.30)
    write("hatch_vent_out", fade(norm(bands) * 0.6, 0.004, 0.10))

    # Closing: the reverse. Repress builds INTO existence as the hold fills.
    count = n(1.1)
    fill = np.zeros(count)
    for i in range(steps):
        lo, hi = i / steps, (i + 1) / steps
        seg = bandpass(noise(count), 240.0 + 2400.0 * lo, 500.0 + 4800.0 * lo, 2)
        mask = np.zeros(count)
        mask[int(lo * count):int(hi * count)] = 1.0
        fill += seg * mask
    fill *= np.linspace(0.15, 1.0, count) ** 1.6
    write("hatch_repress", fade(norm(fill) * 0.55, 0.06, 0.12))

    # Reaching the open stop: the door hits its end and the pins go in.
    canvas = np.zeros(n(1.0))
    place(canvas, thump(0.8, 62.0, 0.32), 0.0)
    place(canvas, click(0.09, 1200.0, 5000.0, 0.014) * 0.4, 0.09)
    write("hatch_latch_open", canvas)

    # Secured: heavier. A door being pulled closed against its seal, then locked.
    canvas = np.zeros(n(1.2))
    place(canvas, thump(0.9, 55.0, 0.38), 0.0)
    place(canvas, click(0.12, 900.0, 4200.0, 0.020) * 0.5, 0.11)
    place(canvas, click(0.08, 1600.0, 6500.0, 0.010) * 0.3, 0.19)
    write("hatch_latch_close", canvas)


# --- Cutter ---------------------------------------------------------------------

def build_cutter():
    """Firing a torch in vacuum is a sequence, not an event.

    The arc itself is silent — it is out there, in nothing. What you get is the
    capacitor bank spooling (inboard, so this one is CRISP), a contactor, the
    conducted crackle of ablation shock coming back down the boom, and a coolant
    pump that keeps running after you let go because the head is still hot.
    """
    # Charge: inboard converter, so it is allowed a top end nothing else has.
    #
    # Long, and deliberately. A capacitor bank of this size is not a switch you
    # throw — the spool is most of what tells the pilot the torch is coming up,
    # and it runs alongside the alignment they are flying rather than finishing
    # before they have taken aim. It is cut short by the contactor if the cut is
    # committed early (see AudioSystem), which is the right way round: firing
    # ends the charge, the charge does not wait to be finished.
    CHARGE = 3.6
    RAMP = 0.86          # fraction of the clip spent climbing; the rest is full
    count = n(CHARGE)
    ramp = int(count * RAMP)

    # Slow to start and steepening, because the converter's switching frequency
    # climbs as the bank fills and the charging current falls away.
    climb = np.linspace(0.0, 1.0, ramp) ** 1.7
    sweep = np.concatenate([climb, np.ones(count - ramp)])
    phase = 2 * np.pi * np.cumsum(430.0 + 1950.0 * sweep) / SR
    whine = 0.6 * np.sin(phase) + 0.25 * np.sin(2 * phase) + 0.1 * np.sin(3 * phase)

    # Switching ripple: the converter's duty cycle beating against the note,
    # easing off as the bank approaches full.
    whine *= 1.0 + 0.14 * (1.0 - sweep) * np.sin(2 * np.pi * 63.0 * t(count))
    whine += 0.12 * np.sin(2 * np.pi * 400.0 * t(count))     # converter buzz
    whine += 0.06 * lowpass(noise(count), 1800.0) * sweep    # coil hiss as it loads

    # Swells while it climbs, then backs off to a steady hold — the bank is full
    # and the converter is only topping it up. That plateau is the "ready" tell.
    level = np.concatenate([
        np.linspace(0.15, 1.0, ramp) ** 1.3,
        np.linspace(1.0, 0.72, count - ramp),
    ])
    write("cutter_charge", fade(norm(whine * level) * 0.7, 0.03, 0.05))

    # Contactor closing. Hard, short, and the loudest single thing in the set.
    canvas = np.zeros(n(0.35))
    place(canvas, click(0.06, 600.0, 8000.0, 0.008), 0.0)
    place(canvas, thump(0.30, 120.0, 0.09) * 0.5, 0.005)
    write("cutter_ignite", canvas)

    # Cutting: the conducted signature. Coolant pump throb under a stochastic
    # crackle, all of it hard-lowpassed because it has come through the frame.
    count = n(2.0)
    pump = 0.30 * np.sin(cycles(count, 46.0))
    pump *= 1.0 + 0.35 * np.sin(cycles(count, 5.5))
    crackle = noise(count)
    # Sparse impulses rather than steady noise — ablation is events, not a hiss.
    gate = (RNG.random(count) < 0.020).astype(float)
    gate = np.convolve(gate, np.exp(-np.linspace(0.0, 6.0, n(0.02))), mode="same")
    crackle = lowpass(crackle * gate, 600.0, 2)
    bed = 0.35 * lowpass(pink(count), 300.0)
    write("cutter_loop", norm(pump + 1.2 * norm(crackle) + bed) * 0.7)

    # Aligning: the targeting beam only. No ablation, so no crackle — just the
    # head powered and the pump idling. Quieter, and it should read as WAITING.
    count = n(2.0)
    idle = 0.30 * np.sin(cycles(count, 46.0))
    idle += 0.10 * np.sin(cycles(count, 690.0)) * (1.0 + 0.2 * np.sin(cycles(count, 6.0)))
    idle += 0.25 * lowpass(pink(count), 240.0)
    write("cutter_align_loop", norm(idle) * 0.45)

    # Shutdown: contactor drops, whine falls away — and the pump RUNS ON, then
    # spins down. The head is still hot; it does not stop because you let go.
    count = n(2.6)
    canvas = np.zeros(count)
    place(canvas, click(0.05, 500.0, 6000.0, 0.007) * 0.8, 0.0)
    fall = np.linspace(1.0, 0.0, count) ** 1.5
    phase = 2 * np.pi * np.cumsum(1500.0 * fall + 90.0) / SR
    canvas += 0.35 * np.sin(phase) * decay(count, 0.35)
    runon = 0.30 * np.sin(2 * np.pi * 46.0 * t(count))
    runon *= np.concatenate([np.ones(n(1.6)), np.linspace(1.0, 0.0, count - n(1.6)) ** 2])
    canvas += runon + 0.2 * lowpass(pink(count), 260.0) * np.concatenate(
        [np.ones(n(1.6)), np.linspace(1.0, 0.0, count - n(1.6)) ** 2])
    write("cutter_stop", fade(norm(canvas) * 0.7, 0.001, 0.08))


# --- Thrusters ------------------------------------------------------------------

def build_thrusters():
    """Two different machines, and neither of them roars.

    RCS is a solenoid valve cracking open, conducted — a dull knock, not a click
    — and then the reaction load going through the mounts while the jet fires.
    The plume makes no sound at all; it is in vacuum.

    The main drive is felt more than heard: sub-200 Hz rumble with a slow
    wander, a turbopump on top, and the frame's own resonance.
    """
    # NOT thump(). A thruster valve has no note.
    #
    # The first version of these built each pop around two sine partials at
    # 185/210/240 Hz — a tuned drum. Three of them cycling round-robin under a
    # pilot working the stick played a little melody: percussion, not plumbing.
    # Everything below is derived from NOISE, so there is nothing to hear a pitch
    # in, and the three variants differ by filter corner and decay rather than by
    # frequency. Whatever order they fire in, no tune comes out.
    for i, (seat_hi, body_lo, body_tau, weight_tau) in enumerate([
            (2600.0, 480.0, 0.030, 0.055),
            (2100.0, 380.0, 0.038, 0.070),
            (3100.0, 560.0, 0.024, 0.045)]):
        count = n(0.18)
        # The seat cracking: broadband, and over almost before it started. This
        # is the only part with any top end, and the frame takes most of it.
        seat = bandpass(noise(count), 400.0, seat_hi) * decay(count, 0.004)
        # The mount taking the reaction load — the part you actually feel.
        body = lowpass(noise(count), body_lo, 2) * decay(count, body_tau)
        # A little weight underneath, still noise: filtered, not oscillated.
        weight = lowpass(noise(count), 140.0, 3) * decay(count, weight_tau)
        canvas = 0.55 * norm(seat) + 1.0 * norm(body) + 0.7 * norm(weight)
        write("rcs_pop_%s" % "abc"[i], fade(canvas, 0.0003, 0.02))

    # Held axis: the sustained reaction load under the pops. No tone here either
    # — the old 62 Hz sine read as a hum from somewhere else in the ship.
    count = n(1.0)
    hold = lowpass(pink(count), 260.0, 2)
    # Irregular, because a jet running against its stop is not smooth. Two slow
    # rates that do not divide into each other, so nothing pulses in time.
    hold *= 1.0 + 0.28 * np.sin(cycles(count, 7.0)) + 0.17 * np.sin(cycles(count, 11.0))
    write("rcs_hold_loop", norm(hold) * 0.45)

    # Main drive, running.
    count = n(3.0)
    rumble = lowpass(pink(count), 150.0, 3)
    rumble = resonance(rumble, 42.0, 2.5, 2.2)      # the frame's own note
    wander = 1.0 + 0.18 * np.sin(cycles(count, 0.7)) + 0.10 * np.sin(cycles(count, 1.9))
    turbo = 0.16 * np.sin(cycles(count, 330.0)) + 0.07 * np.sin(cycles(count, 660.0))
    turbo *= 1.0 + 0.15 * np.sin(cycles(count, 3.0))
    write("drive_loop", norm(norm(rumble) * wander + turbo) * 0.75)

    # Starter crank. Played at a rising pitch_scale across drive_start_time, so
    # the ten-second start is one small loop and not a ten-second file.
    count = n(2.0)
    crank = 0.5 * np.sin(cycles(count, 58.0)) + 0.2 * np.sin(cycles(count, 116.0))
    crank *= 1.0 + 0.40 * np.sin(cycles(count, 6.0))    # the crank's beat
    crank += 0.45 * lowpass(pink(count), 320.0)
    write("drive_crank_loop", norm(crank) * 0.6)

    # The moment it catches.
    count = n(1.4)
    catch = np.zeros(count)
    place(catch, thump(0.9, 58.0, 0.40), 0.0)
    swell = lowpass(pink(count), 200.0) * (np.linspace(0.0, 1.0, count) ** 2)
    write("drive_catch", fade(norm(catch + 0.7 * swell) * 0.8, 0.002, 0.05))

    # Shutdown: it winds down and the frame stops ringing.
    count = n(2.8)
    fall = np.linspace(1.0, 0.06, count) ** 1.3
    phase = 2 * np.pi * np.cumsum(330.0 * fall) / SR
    down = 0.30 * np.sin(phase)
    down += norm(lowpass(pink(count), 150.0, 3)) * fall * 0.8
    write("drive_shutdown", fade(norm(down) * 0.7, 0.01, 0.25))


# --- Annunciator and radio ------------------------------------------------------

def build_alerts():
    """Airborne, from the annunciator panel — which is why they cut through.

    These are the only deliberately piercing sounds on the ship. Everything else
    is either behind a hull or made of air; the warning is meant to be the thing
    you cannot ignore, and it earns that by being the only one with a top end.
    """
    # WARNING: an alternating two-tone warble, looped for as long as it applies.
    # 0.5 s holds exactly two alternations at 4 Hz, so the loop is seamless.
    count = n(0.5)
    swap = (np.sin(cycles(count, 4.0)) > 0).astype(float)
    tone = np.sin(2 * np.pi * 800.0 * t(count)) * (1.0 - swap)
    tone += np.sin(2 * np.pi * 1000.0 * t(count)) * swap
    tone += 0.25 * np.sin(2 * np.pi * 1600.0 * t(count)) * (1.0 - swap)
    write("alert_warning_loop", norm(tone) * 0.8)

    # CAUTION: three chirps and done. Softer, and it does not repeat.
    count = n(0.75)
    canvas = np.zeros(count)
    for i in range(3):
        seg = n(0.09)
        chirp = np.sin(2 * np.pi * 660.0 * t(seg)) * np.sin(np.pi * np.linspace(0, 1, seg))
        place(canvas, chirp, 0.12 * i)
    write("alert_caution", norm(canvas) * 0.6)

    # NOTE: one soft chime, two partials, long tail. Says "look", not "act".
    count = n(0.9)
    chime = np.sin(2 * np.pi * 880.0 * t(count)) * decay(count, 0.22)
    chime += 0.4 * np.sin(2 * np.pi * 1320.0 * t(count)) * decay(count, 0.13)
    write("alert_note", fade(norm(chime) * 0.45, 0.002, 0.10))

    # Incoming call: the two-tone that precedes every transmission, so the
    # harbour always announces itself before it speaks.
    count = n(0.62)
    canvas = np.zeros(count)
    for i, hz in enumerate((1240.0, 890.0)):
        seg = n(0.22)
        pip = np.sin(2 * np.pi * hz * t(seg)) * np.sin(np.pi * np.linspace(0, 1, seg)) ** 0.4
        place(canvas, pip, 0.26 * i)
    write("comms_chirp", norm(canvas) * 0.55)

    # Our own transmit: key down, and the squelch tail on key up.
    write("mic_click_on", click(0.05, 800.0, 5000.0, 0.006) * 0.5)
    count = n(0.28)
    tail = bandpass(noise(count), 400.0, 3000.0) * decay(count, 0.05)
    write("mic_click_off", fade(norm(tail) * 0.4, 0.001, 0.06))

    # The carrier dropping at the end of somebody else's transmission.
    count = n(0.35)
    squelch = bandpass(noise(count), 300.0, 3400.0) * decay(count, 0.07)
    write("squelch_tail", fade(norm(squelch) * 0.45, 0.001, 0.08))


def build_impacts():
    """Hitting something. Scaled at runtime by the closing speed."""
    canvas = np.zeros(n(1.0))
    place(canvas, thump(0.8, 88.0, 0.24) * 0.7, 0.0)
    place(canvas, click(0.12, 500.0, 3000.0, 0.02) * 0.3, 0.005)
    write("impact_soft", canvas)

    canvas = np.zeros(n(1.8))
    place(canvas, thump(1.5, 52.0, 0.55), 0.0)
    place(canvas, thump(0.9, 137.0, 0.20) * 0.6, 0.008)
    place(canvas, click(0.25, 400.0, 4500.0, 0.05) * 0.5, 0.0)
    # The frame keeps talking about it for a moment after.
    count = len(canvas)
    canvas += 0.25 * resonance(lowpass(noise(count), 900.0), 210.0, 8.0, 4.0) * decay(count, 0.45)
    write("impact_hard", canvas)


def main():
    print("Synthesising to %s" % OUT_DIR)
    build_ventilation()
    build_gear()
    build_hatch()
    build_cutter()
    build_thrusters()
    build_alerts()
    build_impacts()
    total = sum(os.path.getsize(os.path.join(OUT_DIR, f))
                for f in os.listdir(OUT_DIR) if f.endswith(".wav"))
    print("Done. %d clips, %.1f KB total." %
          (len([f for f in os.listdir(OUT_DIR) if f.endswith('.wav')]), total / 1024.0))


if __name__ == "__main__":
    main()
